apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-deployment
  labels:
    app: infra-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-app
  template:
    metadata:
      labels:
        app: infra-app
    spec:
      containers:
        - name: infra-container
          image: "nginx:latest"  # Use a static image or update via values.yaml if using Helm
          ports:
            - containerPort: 80
